"""empty message

Revision ID: 5749ae3d596c
Revises: feafbf2106be
Create Date: 2024-08-09 05:40:36.466517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5749ae3d596c'
down_revision = 'feafbf2106be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_pair', ['following_id', 'follower_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_pair', type_='unique')

    # ### end Alembic commands ###
