"""empty message

Revision ID: b0607764665f
Revises: 5e334ab0a688
Create Date: 2024-07-23 05:27:33.962788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0607764665f'
down_revision = '5e334ab0a688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               nullable=True)
        batch_op.alter_column('poster',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('poster',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('release_date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
