"""empty message

Revision ID: feafbf2106be
Revises: aadd9ec8f7e0
Create Date: 2024-08-05 01:55:21.430094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feafbf2106be'
down_revision = 'aadd9ec8f7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accept', sa.Boolean(), nullable=True))
        batch_op.drop_column('accepted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('accept')

    # ### end Alembic commands ###
